### ISSUE TITLE
unable to rename (probably old) credit card statement dated in June 2018

### ISSUE THREAD

**Issue by apollowing** [magnuslu/DBS-Singapore-Bank-Statement-Extraction#1]
Probably extract_table function of pdfplumber wan't able to extract the first table in the pdf and instead return the 2nd table which is shows the breakdown of card points.

<img width="506" alt="image" src="https://github.com/magnuslu/DBS-Singapore-Bank-Statement-Extraction/assets/42193360/b82fa6b1-dc4f-4d6a-a0ac-72db8aeb01f4">

**Comment by magnuslu** [comment]
Fixed.
